// NextJS core
import type { Metadata } from "next";

// Fonts
import { Montserrat, Geist_Mono } from "next/font/google";

// Styles
import "./globals.css";

// Services
import { AuthProvider } from "./services/auth";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className="h-full bg-white dark:bg-gray-900">
      <body
        className={`${montserrat.variable} ${geistMono.variable} h-full antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
